export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const FETCH_PIZZAS = 'FETCH_PIZZAS';
export const PIZZAS_FETCHED = 'PIZZAS_FETCHED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const CART_TOGGLE_LOADING = 'CART_TOGGLE_LOADING';
export const CART_SHOW_LOADING = 'CART_SHOW_LOADING';
export const CART_HIDE_LOADING = 'CART_HIDE_LOADING';
export const UPDATE_CART = 'UPDATE_CART';
export const CART_UPDATED = 'CART_UPDATED';
export const UPDATE_CART_ITEM_QTY = 'UPDATE_CART_ITEM_QTY'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const TOGGLE_CART = 'TOGGLE_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const SHOW_CART = 'SHOW_CART';
export const HIDE_CART = 'HIDE_CART';
export const DO_CHECKOUT = 'DO_CHECKOUT';

export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
